---
version: "3.9"
services:
  webserver:
    image: nginx:1.23
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - webserver-net
  dbserver:
    image: mysql:5.6
    ports:
      - target: 3306
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - webserver-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
networks:
  webserver-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24



      
  